-- RLS'i devre dışı bırak (geliştirme için)
ALTER TABLE tesisler DISABLE ROW LEVEL SECURITY;
ALTER TABLE etkinlikler DISABLE ROW LEVEL SECURITY;
ALTER TABLE haberler DISABLE ROW LEVEL SECURITY;
ALTER TABLE kullanicilar DISABLE ROW LEVEL SECURITY;
